FROM eclipse-temurin:17-jdk-alpine

# Configurar zona horaria
ENV TZ=Europe/Madrid

# Definir opciones de la JVM
ENV JVM_OPTS="-Xms512m -Xmx1024m"

# Directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR de la aplicación
COPY target/scouts-0.0.1-SNAPSHOT.jar /app/app.jar

# Asegurar permisos de ejecución
RUN chmod +x /app/app.jar

# Exponer el puerto de la aplicación
EXPOSE 8080

# Definir el comando de arranque
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
